<?php

/**
 * Implements hook_flush_caches().
 */
function migrate_earthday2011_flush_caches() {
  migrate_earthday2011_register_migrations();
}

function migrate_earthday2011_register_migrations() {
  $common_arguments = array(
    'source_connection' => 'legacy',
    'source_version' => 6,
    'group_name' => 'earthday',
  );

  $node_arguments = array(
    array(
      'class_name' => 'EarthdayStoryMigration',
      'description' => t('Migrate story in Earthday 2011 to news in earthday news.'),
      'machine_name' => 'earthday_news',
      'source_type' => 'story', # 新聞室
      'destination_type' => 'earthday_news',
    ),
    array(
      'class_name' => 'EarthdayTopicsMigration',
      'description' => t('Migrate topics in Earthday 2011 to columns in earthday news.'),
      'machine_name' => 'earthday_topic',
      'source_type' => 'topics', # 焦點專題
      'destination_type' => 'earthday_news',
    ),
    array(
      'class_name' => 'EarthdayEventsMigration',
      'description' => t('Migrate events in Earthday 2011 to earthday join.'),
      'machine_name' => 'earthday_event',
      'source_type' => 'events', # 活動登錄
      'destination_type' => 'earthday_join',
    ),
  );
  foreach ($node_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'], $arguments);
  }

  $file_arguments = $common_arguments + array(
    'description' => t('Migrate files in Earthday 2011'),
    'machine_name' => 'earthday_files',
    'source_dir' => '/var/www/drupal6/files/',
  );
  Migration::registerMigration('DrupalFile6Migration', $file_arguments['machine_name'], $file_arguments);
}
